import { pool } from "@/lib/db";
import type { ResolvedRuleRef } from "./types";

/**
 * Allow-listed table -> primary key column, so a snapshot's resolved_rule_ids
 * (table names generated by our own resolver code, never user input) can be
 * looked back up safely without string-interpolating an arbitrary identifier
 * into SQL.
 */
const EXPLAINABLE_TABLES: Record<string, string> = {
  grade_profile_rules: "rule_id",
  material_size_guides: "size_guide_id",
  raw_bar_stock: "stock_id",
  dies_cost_guides: "dies_cost_id",
  price_per_kg: "price_id",
  grade_price_aliases: "alias_id",
  adjustment_rules: "adjustment_rule_id",
  coating_price_guides: "coating_rule_id",
  trading_items: "trading_item_id",
  trading_price_tiers: "tier_id",
  calculation_formulas: "formula_id",
  material_grade_map: "map_id",
  costing_route_rules: "route_rule_id",
};

export type ExplainedRule = ResolvedRuleRef & { row: Record<string, unknown> | null };

/**
 * Resolves a snapshot's resolved_rule_ids back into the actual master-data
 * rows that produced the price, so a finalized line is reconstructable in
 * human-readable form, not just as opaque IDs (AUD-004/AT-AUDIT-002).
 */
export async function explainResolvedRules(refs: ResolvedRuleRef[]): Promise<ExplainedRule[]> {
  const results: ExplainedRule[] = [];
  for (const ref of refs) {
    const idColumn = EXPLAINABLE_TABLES[ref.table];
    if (!idColumn) {
      results.push({ ...ref, row: null });
      continue;
    }
    const { rows } = await pool.query(`SELECT * FROM ${ref.table} WHERE ${idColumn} = $1`, [ref.id]);
    results.push({ ...ref, row: rows[0] ?? null });
  }
  return results;
}
